//==============================================================================
// tb_nli_engine - Testbench for NLI Inference Engine
//
// Loads LUT configuration from .mem files (generated by gen_nli_mem.py),
// feeds test vectors, and compares HW output against Python reference.
//==============================================================================

`timescale 1ns/1ps

module tb_nli_engine;

    // Parameters
    localparam CLK_PERIOD = 10;  // 100 MHz
    localparam M          = 11;
    localparam NUM_INTERVALS = 10;
    localparam D_N        = 32;
    localparam LUT_DEPTH  = 259;
    localparam PIPELINE_LATENCY = 4;

    // DUT signals
    reg         clk, rst_n;
    reg         i_valid;
    reg  [15:0] i_data;
    wire        o_valid;
    wire [15:0] o_data;

    reg         cfg_we;
    reg  [1:0]  cfg_sel;
    reg  [8:0]  cfg_addr;
    reg  [15:0] cfg_wdata;

    // Instantiate DUT
    nli_engine #(
        .D_N(D_N),
        .M(M),
        .NUM_INTERVALS(NUM_INTERVALS),
        .LUT_DEPTH(LUT_DEPTH)
    ) u_dut (
        .clk      (clk),
        .rst_n    (rst_n),
        .i_valid  (i_valid),
        .i_data   (i_data),
        .o_valid  (o_valid),
        .o_data   (o_data),
        .cfg_we   (cfg_we),
        .cfg_sel  (cfg_sel),
        .cfg_addr (cfg_addr),
        .cfg_wdata(cfg_wdata)
    );

    // Clock generation
    initial clk = 0;
    always #(CLK_PERIOD/2) clk = ~clk;

    // Memory for configuration data
    reg [15:0] point_mem [0:M-1];
    reg [15:0] mul_mem   [0:NUM_INTERVALS-1];
    reg [15:0] lut_mem   [0:LUT_DEPTH-1];

    // Test vector memory
    localparam MAX_TESTS = 1024;
    reg [15:0] test_input  [0:MAX_TESTS-1];
    reg [15:0] test_expect [0:MAX_TESTS-1];
    integer    num_tests;

    // Statistics
    integer total_tests, pass_count, fail_count;
    integer max_ulp_err;

    // =========================================================================
    // Helper: compute ULP distance between two FP16 values
    // =========================================================================
    function automatic integer ulp_distance;
        input [15:0] a, b;
        reg signed [16:0] a_int, b_int;
        begin
            // Convert to signed magnitude integer for ULP comparison
            a_int = a[15] ? -(a[14:0]) : a[14:0];
            b_int = b[15] ? -(b[14:0]) : b[14:0];
            ulp_distance = (a_int > b_int) ? (a_int - b_int) : (b_int - a_int);
        end
    endfunction

    // =========================================================================
    // Helper: FP16 bits to real (for display)
    // =========================================================================
    function automatic real fp16_to_real;
        input [15:0] bits;
        reg sign;
        reg [4:0] exp_val;
        reg [9:0] mant_val;
        real result;
        begin
            sign = bits[15];
            exp_val = bits[14:10];
            mant_val = bits[9:0];
            if (exp_val == 0 && mant_val == 0)
                result = 0.0;
            else if (exp_val == 0)
                result = (2.0**(-14)) * (mant_val / 1024.0);  // subnormal
            else if (exp_val == 31)
                result = (mant_val == 0) ? 1.0/0.0 : 0.0/0.0;  // inf/nan
            else
                result = (2.0**(exp_val - 15)) * (1.0 + mant_val / 1024.0);
            fp16_to_real = sign ? -result : result;
        end
    endfunction

    // =========================================================================
    // Main test sequence
    // =========================================================================
    integer i, j;

    initial begin
        $dumpfile("nli_engine.vcd");
        $dumpvars(0, tb_nli_engine);

        // Initialize
        rst_n    = 0;
        i_valid  = 0;
        i_data   = 0;
        cfg_we   = 0;
        cfg_sel  = 0;
        cfg_addr = 0;
        cfg_wdata = 0;

        // Load configuration data from .mem files
        $readmemh("point_reg.mem", point_mem);
        $readmemh("mul_reg.mem",   mul_mem);
        $readmemh("lut_reg.mem",   lut_mem);

        // Load test vectors
        begin
            reg [31:0] tv_mem [0:MAX_TESTS*2-1];
            $readmemh("test_vectors.mem", tv_mem);
            num_tests = 0;
            for (i = 0; i < MAX_TESTS; i = i + 1) begin
                if (tv_mem[i*2] !== 32'hxxxxxxxx) begin
                    test_input[i]  = tv_mem[i*2][15:0];
                    test_expect[i] = tv_mem[i*2+1][15:0];
                    num_tests = num_tests + 1;
                end
            end
        end

        $display("=== NLI Engine Testbench ===");
        $display("  Loaded %0d test vectors", num_tests);

        // Reset
        repeat(5) @(posedge clk);
        rst_n = 1;
        repeat(2) @(posedge clk);

        // ---- Phase 1: Load configuration ----
        $display("[Phase 1] Loading configuration registers...");

        // Load point_reg (11 entries)
        for (i = 0; i < M; i = i + 1) begin
            @(negedge clk);
            cfg_we    = 1;
            cfg_sel   = 2'd0;
            cfg_addr  = i[8:0];
            cfg_wdata = point_mem[i];
        end
        @(negedge clk);
        cfg_we = 0;

        // Load mul_reg (10 entries)
        for (i = 0; i < NUM_INTERVALS; i = i + 1) begin
            @(negedge clk);
            cfg_we    = 1;
            cfg_sel   = 2'd1;
            cfg_addr  = i[8:0];
            cfg_wdata = mul_mem[i];
        end
        @(negedge clk);
        cfg_we = 0;

        // Load lut_reg (259 entries)
        for (i = 0; i < LUT_DEPTH; i = i + 1) begin
            @(negedge clk);
            cfg_we    = 1;
            cfg_sel   = 2'd2;
            cfg_addr  = i[8:0];
            cfg_wdata = lut_mem[i];
        end
        @(negedge clk);
        cfg_we = 0;

        $display("  Configuration loaded.");
        repeat(5) @(posedge clk);

        // ---- Phase 2: Feed test vectors ----
        $display("[Phase 2] Running %0d test vectors...", num_tests);

        total_tests = 0;
        pass_count  = 0;
        fail_count  = 0;
        max_ulp_err = 0;

        // Feed all inputs (one per cycle, driven after negedge to avoid race)
        fork
            // Producer: feed inputs at negedge (setup time for next posedge)
            begin
                for (i = 0; i < num_tests; i = i + 1) begin
                    @(negedge clk);
                    i_valid = 1;
                    i_data  = test_input[i];
                end
                @(negedge clk);
                i_valid = 0;
                i_data  = 16'h0000;
            end

            // Consumer: check outputs (read after small delay past posedge)
            begin
                // Wait for pipeline latency minus 1:
                // repeat(N) counts from the same posedge where DUT samples first input
                // After N posedges + 1 more @posedge in the for loop = N+1 total
                // We need PIPELINE_LATENCY posedges from sample to output, so N = PIPELINE_LATENCY - 1
                repeat(PIPELINE_LATENCY - 1) @(posedge clk);

                for (j = 0; j < num_tests; j = j + 1) begin
                    @(posedge clk);
                    #1;  // let NBA settle
                    if (o_valid) begin
                        total_tests = total_tests + 1;
                        begin
                            integer ulp;
                            ulp = ulp_distance(o_data, test_expect[j]);
                            if (ulp > max_ulp_err)
                                max_ulp_err = ulp;

                            if (ulp <= 2) begin
                                pass_count = pass_count + 1;
                            end else begin
                                fail_count = fail_count + 1;
                                if (fail_count <= 20) begin
                                    $display("  MISMATCH [%0d]: input=%04h got=%04h (%.4f) exp=%04h (%.4f) ulp=%0d",
                                        j, test_input[j],
                                        o_data, fp16_to_real(o_data),
                                        test_expect[j], fp16_to_real(test_expect[j]),
                                        ulp);
                                end
                            end
                        end
                    end
                end
            end
        join

        // Wait for remaining pipeline outputs
        repeat(PIPELINE_LATENCY + 2) @(posedge clk);

        // ---- Results ----
        $display("");
        $display("=== Results ===");
        $display("  Total: %0d, Pass: %0d, Fail: %0d", total_tests, pass_count, fail_count);
        $display("  Max ULP error: %0d", max_ulp_err);
        $display("  Pass rate: %0.1f%%",
            (total_tests > 0) ? (100.0 * pass_count / total_tests) : 0.0);

        if (fail_count == 0)
            $display("  >>> ALL TESTS PASSED <<<");
        else
            $display("  >>> SOME TESTS FAILED <<<");

        $display("");
        repeat(10) @(posedge clk);
        $finish;
    end

    // Timeout
    initial begin
        #(CLK_PERIOD * (MAX_TESTS + 500));
        $display("ERROR: Simulation timeout!");
        $finish;
    end

endmodule
